#! /bin/sh

set +x 

hex=$1
hexln=$(cat $hex | wc -l)
hexln=$(($hexln - 1))

head -n $hexln $hex | sed 's///g'

bt=${2:-"optiboot_atmega328.hex"}
btln=$(cat $bt | wc -l)
btln=$(($btln - 2))
head -n $btln $bt | sed 's///g'

echo ":00000001FF"

